import React, {useEffect, useRef, useState} from 'react';
import logo from '../assets/agilisium-primary.png';
import {useResource, number, dateTime, queryString} from './data';
import {Trend, Bars} from './Charts';
import {Source, Status, Review} from './Evidence';

import './reginsight.css';

const pipeline = ['Raw inspection data','Data standardization','Observation classification','Theme detection','Severity assessment','Recurrence analysis','Risk scoring','Evidence traceability','Human review'];
const architecture = [
  ['01','Source & ingestion','Regulatory inspection exports','CSV, Excel and Parquet retain source identifiers and row provenance.'],
  ['02','Data engineering','PySpark ETL · validation','Schema mapping, duplicate handling and quarantine precede analytical use.'],
  ['03','Structured storage','Parquet · PostgreSQL / SQLite','Portable columnar data and a queryable inspection store; SQLite supports local operation.'],
  ['04','Intelligence','LLM adapters · embeddings · similarity','Configured providers interpret observations. Validated rules remain an explicit fallback. Retrieval links explanations to evidence.'],
  ['05','Application','FastAPI · Pydantic · React','Typed REST APIs connect interactive analytics, evidence inspection and human review.'],
];

function Dialog({title, children, onClose}) {
  const ref = useRef(null);
  useEffect(() => {
    const previous = document.activeElement;
    ref.current.showModal();
    return () => previous?.focus();
  }, []);
  return <dialog ref={ref} className="ri-dialog" onCancel={onClose} onClick={e => {if(e.target === e.currentTarget) onClose();}} aria-labelledby="dialog-title"><div className="ri-section-heading"><h2 id="dialog-title">{title}</h2><button className="ri-button" onClick={onClose}>Close</button></div>{children}</dialog>;
}

function Feedback({resource, retry}) {
  if (resource.loading) return <div role="status" className="ri-empty">Retrieving the inspection snapshot…</div>;
  if (resource.error) return <div className="ri-empty ri-error" role="alert"><strong>Data connection unavailable</strong><p>{resource.error}</p><button className="ri-button" onClick={retry}>Retry connection</button></div>;
  return null;
}

function Documentation() {
  return <div className="ri-document"><p>RegInsight AI connects structured inspection data, observation interpretation, evidence retrieval and expert review.</p><h3>Working with the data</h3><p>Select a dataset, search across observation text, company, facility or inspection ID, and filter by severity, fiscal year or theme. Table sorting is performed across the entire filtered result. Annual citation templates are excluded from this inspection workspace.</p><h3>Understanding the measures</h3><dl><dt>Analytical severity</dt><dd>A validated classification of observation text. It is not an agency determination.</dd><dt>Recurrence</dt><dd>Related text linked to multiple inspections. A candidate for investigation, not a confirmed repeated violation.</dd><dt>Portfolio risk</dt><dd>A separate heuristic calculated from available inspection factors. Missing factors are excluded and coverage must be considered.</dd></dl><h3>Evidence and reviews</h3><p>Choose a record to see the original observation, matched quote, source workbook, row and assessment timestamp. Human decisions are appended to review history without overwriting the original classification. Reviewer identities are self-reported in this local deployment.</p><h3>Deployment</h3><p>Run the included FastAPI service to enable live data, search, evidence and reviews. Source data must be imported and an observation-intelligence snapshot built. Production authentication and organization-specific retention controls require deployment configuration.</p><a href="/docs" target="_blank" rel="noreferrer">Open interactive API documentation ↗</a></div>;
}

export default function RegInsight() {
  const [refresh,setRefresh] = useState(0), [tab,setTab] = useState('Overview'), [menu,setMenu] = useState(false);
  const [dataset,setDataset] = useState('real'), [search,setSearch] = useState(''), [draft,setDraft] = useState('');
  const [severity,setSeverity] = useState(''), [year,setYear] = useState(''), [theme,setTheme] = useState('');
  const [sort,setSort] = useState('severity'), [direction,setDirection] = useState('desc'), [offset,setOffset] = useState(0);
  const [selected,setSelected] = useState(null), [modal,setModal] = useState(null), [evidenceView,setEvidenceView] = useState('Source');
  useEffect(() => {
    function shortcut(event) {
      if (event.key === '/' && !event.ctrlKey && !event.metaKey && !event.altKey &&
          !event.target.closest('input, textarea, select, [contenteditable="true"], dialog')) {
        event.preventDefault(); setTab('Observations'); setMenu(false);
        document.getElementById('workspace')?.scrollIntoView({behavior:'instant'});
        setTimeout(() => document.getElementById('inspection-search')?.focus(), 0);
      }
    }
    window.addEventListener('keydown', shortcut);
    return () => window.removeEventListener('keydown', shortcut);
  }, []);
  const summary = useResource('/workspace/summary?' + queryString({dataset}), refresh);
  const portfolio = useResource('/dashboard', refresh);
  const page = useResource(summary.data ? '/workspace/observations?' + queryString({dataset,run_id:summary.data.run_id,search,severity,year,theme,sort,direction,offset,limit:8}) : null, refresh);
  const related = useResource(selected && evidenceView==='Related' ? '/observations/similar/' + encodeURIComponent(selected.observation_id) + '?' + queryString({run_id:summary.data?.run_id}) : null);
  useEffect(() => {
    if (page.data?.records.length) setSelected(previous => previous
      ? page.data.records.find(r => r.observation_id === previous.observation_id) || previous
      : page.data.records[0]);
  }, [page.data]);
  function resetSelection() {setOffset(0); setSelected(null);}
  function openWorkspace(next='Observations') {setTab(next); setMenu(false); document.getElementById('workspace')?.scrollIntoView({behavior:'instant',block:'start'});}
  function selectRecord(record) {setSelected(record); setEvidenceView('Source');}
  function sortBy(key) {setSort(key); setDirection(sort===key && direction==='desc' ? 'asc' : 'desc'); setOffset(0);}
  function clear() {setDraft('');setSearch('');setSeverity('');setYear('');setTheme('');resetSelection();}
  const stats = summary.data?.stats;
  const risks = portfolio.data ? Object.entries(portfolio.data.risk_distribution || {}).map(([label,count]) => ({label,count})) : [];
  const highRisk = portfolio.data ? portfolio.data.attention_sites : null;
  const themeRows = summary.data?.themes.filter(r => r.theme!=='Unclassified') || [];
  const selectTheme = name => {setTheme(name);setOffset(0);setSelected(null);setTab('Observations');};
  const noData = !summary.data;
  return <div className="ri-site">
    <a className="ri-skip" href="#main-content">Skip to main content</a>
    <header className="ri-header"><div className="ri-header-main">
      <a className="ri-brand" href="#overview" aria-label="Agilisium, RegInsight AI home"><span className="ri-logo"><img src={logo} width="765" height="401" alt="Agilisium: Insights. Humanity. Impact."/></span><span className="ri-brand-divider"/><strong>RegInsight <span>AI</span></strong></a>
      <div className="ri-header-actions"><button onClick={() => {openWorkspace(); setTimeout(() => document.getElementById('inspection-search')?.focus(),0);}}>Search <span className="ri-key" aria-hidden="true">/</span></button><button onClick={() => setModal('Documentation')}>Documentation</button><button onClick={() => setModal('Sign In')}>Sign In</button><button className="ri-button primary" onClick={() => openWorkspace()}>Open Workspace <span aria-hidden="true">↗</span></button></div>
      <button className="ri-mobile-menu ri-button" aria-expanded={menu} aria-controls="main-navigation" onClick={() => setMenu(!menu)}>Menu</button>
    </div><nav id="main-navigation" className={menu ? 'ri-nav open' : 'ri-nav'} aria-label="Primary navigation"><a href="#overview" onClick={() => setMenu(false)}>Overview</a><button onClick={() => openWorkspace('Observations')}>Inspection Intelligence</button><a href="#risk" onClick={() => setMenu(false)}>Risk Analysis</a><a href="#evidence" onClick={() => setMenu(false)}>Evidence</a><button onClick={() => openWorkspace('Overview')}>Analytics</button><div className="ri-mobile-utilities"><button onClick={()=>{setMenu(false);openWorkspace();setTimeout(()=>document.getElementById('inspection-search')?.focus(),0);}}>Search</button><button onClick={()=>{setMenu(false);setModal('Documentation');}}>Documentation</button><button onClick={()=>{setMenu(false);setModal('Sign In');}}>Sign In</button></div><span>REGULATORY INSPECTION INTELLIGENCE</span></nav></header>
    <main id="main-content">
      <section className="ri-hero ri-shell" id="overview"><div><span className="ri-overline">Evidence-led quality intelligence</span><h1>Regulatory inspection intelligence for earlier risk visibility.</h1></div><div className="ri-hero-copy"><p>Connect inspection observations to structured themes, recurrence patterns and explainable risk. Keep the evidence in view, and expert judgment in control.</p><div className="ri-hero-actions"><button className="ri-button primary" onClick={() => openWorkspace()}>Open Intelligence Workspace <span aria-hidden="true">↗</span></button><a href="#methodology">Explore the methodology</a></div></div></section>
      <section id="workspace" className="ri-workspace ri-shell" aria-label="Inspection intelligence workspace">
        <div className="ri-workspace-title"><div><span className="ri-workspace-mark" aria-hidden="true">RI</span><h2>Inspection Intelligence</h2><span className="ri-mono">Workspace / {tab}</span></div><span className="ri-live">{summary.data ? 'Connected snapshot' : summary.loading ? 'Connecting' : 'Connection required'}</span></div>
        <div className="ri-workspace-meta"><span>{dataset==='real' ? 'User-supplied inspection exports' : dataset==='demo' ? 'Synthetic demonstration corpus' : 'Synthetic inspection corpus'}</span><span>{summary.data ? `Snapshot ${dateTime(summary.data.created_at)}` : 'Snapshot pending'}<button className="ri-text-button" onClick={() => setRefresh(v=>v+1)}>Refresh</button></span></div>
        <div className="ri-kpis">{[['Inspections with observations',stats?.inspections,'Distinct inspection IDs in this corpus'],['Source observations',stats?.observations,'Inspection records; annual templates excluded'],['Recurring themes',stats?.recurring_themes,'Themes present in multiple inspections'],['High-risk sites',highRisk,'High + critical; separate inspection portfolio']].map(([label,value,note],i) => <div key={label}><span>{label}</span><strong className={i===3 ? 'ri-risk-number' : ''}>{value==null ? '…' : number(value)}</strong><small>{note}</small></div>)}</div>
        <div className="ri-console-tabs" role="tablist" aria-label="Workspace view">{['Overview','Observations','Risk analysis'].map(v => <button key={v} id={'tab-'+v.replaceAll(' ','-')} role="tab" aria-selected={tab===v} aria-controls="workspace-panel" tabIndex={tab===v?0:-1} onKeyDown={e => {if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const all=['Overview','Observations','Risk analysis'];const next=e.key==='Home'?0:e.key==='End'?2:(all.indexOf(v)+(e.key==='ArrowRight'?1:2))%3;setTab(all[next]);document.getElementById('tab-'+all[next].replaceAll(' ','-'))?.focus();}}} onClick={() => setTab(v)}>{v}{v==='Observations' && stats && <span aria-hidden="true">{number(stats.observations)}</span>}</button>)}<span className="ri-console-note">Human oversight required</span></div>
        <div className={'ri-console-body '+(tab==='Observations' ? 'wide' : '')}>
          <div id="workspace-panel" role="tabpanel" aria-labelledby={'tab-'+tab.replaceAll(' ','-')} className="ri-workspace-content">
            <Feedback resource={summary} retry={() => setRefresh(v=>v+1)}/>
            {!noData && tab==='Overview' && <><div className="ri-section-heading"><div><h3>Observation trend</h3><p>Inspection-level evidence across fiscal years</p></div><span className="ri-mono">{summary.data.trend[0]?.year} / {summary.data.trend.at(-1)?.year}</span></div><Trend rows={summary.data.trend}/><div className="ri-chart-pair"><div><h3>Theme concentration</h3><Bars rows={themeRows.slice(0,4).map(r=>({label:r.theme,count:r.count}))} onSelect={selectTheme}/></div><div><h3>Recurrence analysis</h3><Bars rows={themeRows.filter(r=>r.inspections>1).slice(0,4).map(r=>({label:r.theme,count:r.inspections}))} onSelect={selectTheme}/><p className="ri-note">Distinct inspections with the same theme. Similarity requires expert review.</p></div></div></>}
            {!noData && tab==='Risk analysis' && <><div className="ri-section-heading"><div><h3>Prioritize with context</h3><p>Risk factors and text severity remain separate.</p></div></div><div className="ri-chart-pair"><div><h3>Site risk distribution</h3><Feedback resource={portfolio} retry={() => setRefresh(v=>v+1)}/><Bars rows={risks} semantic/><p className="ri-note">Entire inspection portfolio, as of {portfolio.data?.info.as_of || 'unavailable'}. Scores are prioritization heuristics.</p></div><div><h3>Observation severity</h3><Bars rows={summary.data.severity} semantic/><p className="ri-note">Selected observation corpus. {summary.data.provider==='rules' ? 'Rule-derived' : 'Provider-derived'} classification, not a regulatory determination.</p></div></div></>}
            {!noData && tab==='Observations' && <><form className="ri-filters" onSubmit={e=>{e.preventDefault();setSearch(draft);resetSelection();}}><label className="ri-search-label">Search inspection evidence<input id="inspection-search" value={draft} maxLength={200} onChange={e=>setDraft(e.target.value)} placeholder="Observation, facility or inspection ID"/></label><label>Severity<select value={severity} onChange={e=>{setSeverity(e.target.value);resetSelection();}}><option value="">All severities</option>{['Critical','High','Medium','Low','Unclassified'].map(v=><option key={v}>{v}</option>)}</select></label><label>Fiscal year<select value={year} onChange={e=>{setYear(e.target.value);resetSelection();}}><option value="">All years</option>{[...summary.data.trend].reverse().map(r=><option key={r.year}>{r.year}</option>)}</select></label><button className="ri-button">Search</button><button type="button" className="ri-text-button" onClick={clear}>Reset</button></form>
              <div className="ri-filter-secondary"><label>Dataset<select value={dataset} onChange={e=>{setDataset(e.target.value);clear();}}><option value="real">Supplied inspection data</option><option value="demo">Synthetic demonstration</option><option value="synthetic">Synthetic inspections</option></select></label><label>Theme<select value={theme} onChange={e=>{setTheme(e.target.value);resetSelection();}}><option value="">All themes</option>{summary.data.themes.map(r=><option key={r.theme}>{r.theme}</option>)}</select></label><span className="ri-mono">{page.data ? `${number(page.data.total)} matching records` : 'Querying records…'}</span></div>
              <Feedback resource={page} retry={()=>setRefresh(v=>v+1)}/>
              {page.data && <><div className="ri-table-scroll" tabIndex={0} role="region" aria-label="Inspection observations table"><table className="ri-inspection-table"><caption>Inspection observations. Select an inspection to read evidence. Dates use source fiscal year.</caption><thead><tr>{[['Inspection','inspection'],['Date / FY','date'],['Facility','facility'],['Observation',null],['Theme','theme'],['Severity','severity'],['Recurrence',null],['Risk',null],['Status',null]].map(([label,key])=><th key={label} aria-sort={key && sort===key ? direction==='asc'?'ascending':'descending' : undefined}>{key ? <button onClick={()=>sortBy(key)}>{label} {sort===key?(direction==='asc'?'↑':'↓'):''}</button>:label}</th>)}</tr></thead><tbody>{page.data.records.map(r=><tr key={r.observation_id} className={selected?.observation_id===r.observation_id?'selected':''}><td><button className="ri-record-link" onClick={()=>selectRecord(r)} aria-label={'Inspect '+r.inspection_id+' '+r.tag.theme}>{r.inspection_id || r.observation_id}<small>View evidence ↗</small></button></td><td>FY {r.fiscal_year || 'Unknown'}</td><td>{r.company || 'Not supplied'}<small>FEI / site {r.site || 'not supplied'}</small></td><td><span className="ri-table-excerpt">{r.original_text}</span></td><td>{r.tag.theme}</td><td><Status value={r.tag.severity}/></td><td>{r.related_inspections>1 ? `${number(r.related_inspections)} inspections` : 'Single inspection'}<small>Related text</small></td><td>Not scored</td><td>{r.review ? r.review.action==='Approve'?'Approved':r.review.action==='Modify'?'Modified':'Rejected' : 'Needs review'}</td></tr>)}</tbody></table></div>{!page.data.records.length && <div className="ri-empty"><h3>No observations match these filters.</h3><p>Try a broader search or clear the filters.</p><button className="ri-button" onClick={clear}>Clear filters</button></div>}<div className="ri-pagination"><span>{page.data.total?offset+1:0}–{Math.min(offset+8,page.data.total)} of {number(page.data.total)}</span><div><button className="ri-button" disabled={offset===0 || page.loading} onClick={()=>setOffset(Math.max(0,offset-8))}>Previous</button><button className="ri-button" disabled={offset+8>=page.data.total || page.loading} onClick={()=>setOffset(offset+8)}>Next</button></div></div></>}
            </>}
          </div>
          <aside className="ri-evidence-panel" aria-label="Selected observation evidence"><div className="ri-section-heading"><h3>Evidence inspector</h3><span className="ri-mono">01 / Source</span></div><Source record={selected} compact/>{selected && <><p className="ri-note">{selected.tag.ai_generated?'AI-assisted':'Rule-derived'} assessment · {selected.review ? 'Latest decision: '+selected.review.action : 'Review required'}</p><a className="ri-button evidence-button" href="#evidence">Inspect full evidence <span aria-hidden="true">↗</span></a></>}</aside>
        </div><div className="ri-console-footer"><span>Source → interpretation → expert review</span><span>{summary.data ? `Snapshot ${summary.data.run_id.slice(0,8)} · ${summary.data.provider}` : 'No data substituted'}</span></div>
      </section>
      <div className="ri-shell ri-under-console"><span>Built for clinical quality, regulatory affairs and compliance teams.</span><span>Original evidence preserved. Human judgment retained.</span></div>
      <section id="methodology" className="ri-section ri-shell ri-methodology"><div className="ri-section-intro"><span className="ri-overline">01 / The analytical pathway</span><h2>From source data<br/>to a defensible decision.</h2><p>Inspection observations carry signals that are difficult to compare at scale. A structured workflow connects each interpretation to the record that supports it.</p><a href="#architecture">Explore the architecture ↗</a></div><div className="ri-pipeline">{pipeline.map((step,i)=><div key={step}><span className="ri-mono">{String(i+1).padStart(2,'0')}</span><span>{step}</span>{i===8?<small>Expert decision</small>:<span aria-hidden="true">↓</span>}</div>)}<p className="ri-note">AI assists quality professionals. Regulatory judgment remains with qualified human reviewers.</p></div></section>
      <section id="risk" className="ri-section ri-tonal"><div className="ri-shell"><div className="ri-wide-heading"><div><span className="ri-overline">02 / Risk & recurrence</span><h2>See the pattern.<br/>Understand the priority.</h2></div><p>Assess the distribution of risk alongside severity and repeated themes. Inspect coverage and source context before deciding where to focus.</p></div><div className="ri-risk-layout"><div><div className="ri-section-heading"><h3>Site risk distribution</h3><span className="ri-mono">Portfolio</span></div><Feedback resource={portfolio} retry={()=>setRefresh(v=>v+1)}/><Bars rows={risks} semantic/><p className="ri-note">{portfolio.data?.info.data_label || 'Awaiting portfolio data'}. As of {portfolio.data?.info.as_of || 'unavailable'}.</p></div><div><div className="ri-section-heading"><h3>Analytical severity</h3><span className="ri-mono">Observation corpus</span></div><Bars rows={summary.data?.severity || []} semantic/><p className="ri-note">{number(stats?.high_severity)} high or critical text classifications. These do not change the portfolio risk formula.</p></div></div><div className="ri-principles"><p><strong>Defined factors</strong>Risk uses available inspection indicators and a versioned methodology.</p><p><strong>Visible limitations</strong>Missing data reduces coverage. Unclassified text stays visible for review.</p><p><strong>Facility context</strong>Site identifiers stay linked to observations and source records.</p></div></div></section>
      <section id="architecture" className="ri-section ri-architecture"><div className="ri-shell"><div className="ri-wide-heading"><div><span className="ri-overline">Data foundation</span><h2>Engineered for traceability.<br/>Structured for investigation.</h2></div><p>A clear separation between data preparation, analytical computation, AI interpretation and human review.</p></div><div className="ri-architecture-table">{architecture.map(([n,label,tech,copy])=><div key={n}><span className="ri-mono">{n}</span><h3>{label}</h3><div><strong>{tech}</strong><p>{copy}</p></div></div>)}</div><p className="ri-note">Local deployment uses SQLite. PostgreSQL and optional model providers are supported configurations. Observation grouping and grounded explanations depend on the configured data and provider.</p></div></section>
      <section className="ri-section ri-shell ri-context"><span className="ri-overline">Regulated-environment principles</span><h2>Designed with regulated-environment<br/>principles in mind.</h2><p>Risk-based quality management, critical-to-quality thinking, data integrity, human oversight and traceability inform the workflow. This prototype is not formally validated and makes no regulatory compliance claim.</p><div>{['ICH E6(R3)','Risk-Based Quality Management','Critical to Quality','ALCOA+','21 CFR Part 11','Human Oversight','Audit Trails','Explainability','Evidence Traceability'].map(v=><span key={v}>{v}</span>)}</div></section>
      <section id="evidence" className="ri-section ri-shell"><div className="ri-wide-heading"><div><span className="ri-overline">03 / Evidence & traceability</span><h2>Every important insight<br/>has a source.</h2></div><p>Follow the reason, inspect related observations, and return to the original record. Review decisions build on evidence rather than obscuring it.</p></div><div className="ri-trace-path" aria-label="Evidence traceability path">{['Insight','Reason','Related observations','Original source','Timestamp / record','Human review'].map((v,i)=><React.Fragment key={v}><span>{v}</span>{i<5&&<span aria-hidden="true">→</span>}</React.Fragment>)}</div><div className="ri-review-layout"><div className="ri-evidence-detail"><div className="ri-detail-tabs" aria-label="Evidence views">{['Source','Reason','Related'].map(v=><button key={v} aria-pressed={evidenceView===v} onClick={()=>setEvidenceView(v)}>{v}</button>)}</div>{evidenceView==='Source' && <Source record={selected}/>}{evidenceView==='Reason' && (selected ? <><span className="ri-overline">Assessment rationale</span><h3>{selected.tag.theme}</h3><p>{selected.tag.rationale}</p><blockquote className="ri-quote">{selected.tag.evidence_quote}</blockquote><p className="ri-note">Quote matched against normalized source text. Taxonomy {selected.tag.taxonomy_version}; prompt {selected.tag.prompt_version}.</p><dl className="ri-facts"><div><dt>Group</dt><dd>{selected.observation_group_id}</dd></div><div><dt>Method</dt><dd>{selected.grouping_method}</dd></div><div><dt>Similarity</dt><dd>{selected.similarity_score.toFixed(3)} to group representative</dd></div></dl></> : <p className="ri-empty">Select an observation first.</p>)}{evidenceView==='Related' && <><Feedback resource={related} retry={()=>setEvidenceView('Source')}/><p className="ri-note">Up to 20 candidate records from the same similarity group. Related wording is not regulatory equivalence.</p>{related.data?.records.map(r=><button className="ri-related-record" key={r.observation_id} onClick={()=>selectRecord(r)}><strong>{r.company || 'Company not supplied'}</strong><span>{r.original_text}</span><small>FY {r.fiscal_year} · {r.tag.theme} · {r.dataset}</small></button>)}{related.data?.records.length===0&&<p>No related records in this snapshot.</p>}</>}</div><div><span className="ri-overline">04 / Human oversight</span><Review record={selected} runId={summary.data?.run_id} onSaved={()=>setRefresh(v=>v+1)}/></div></div></section>
    </main>
    <footer className="ri-footer"><div className="ri-shell"><div><strong>RegInsight AI</strong><p>Regulatory Inspection Intelligence</p><span>By Agilisium</span></div><nav aria-label="Footer navigation"><button onClick={()=>openWorkspace()}>Inspection Intelligence</button><button onClick={()=>setModal('Documentation')}>Documentation</button><a href="#methodology">Methodology</a><button onClick={()=>setModal('Contact')}>Contact</button><button onClick={()=>setModal('Terms of Service')}>Terms of Service</button><button onClick={()=>setModal('Privacy Policy')}>Privacy Policy</button></nav></div><div className="ri-shell ri-footer-bottom"><span>Evidence informs. Experts decide.</span><span>Research prototype · Local workspace</span></div></footer>
    {modal && <Dialog title={modal} onClose={()=>setModal(null)}>{modal==='Documentation' ? <Documentation/> : modal==='Sign In' ? <><p>Organization sign-in has not been configured for this local deployment.</p><p>No credentials are collected here. The workspace is available locally; production access requires an organization identity provider.</p><button className="ri-button primary" onClick={()=>{setModal(null);openWorkspace();}}>Continue to local workspace</button></> : modal==='Contact' ? <><p>A contact destination has not been supplied.</p><p>Contact your deployment owner or Agilisium project representative through your existing approved channel.</p></> : <><span className="ri-overline">Placeholder destination</span><p>{modal} content has not been supplied. This page does not establish legal terms or describe a verified privacy policy.</p><p>The deployment owner must provide the applicable policy before public use.</p></>}</Dialog>}
  </div>;
}
